services:
  postgres:
    image: postgres:16-alpine
    container_name: rotas_ml_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rotas_ml
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - rotas_ml_pgdata:/var/lib/postgresql/data

volumes:
  rotas_ml_pgdata:
